// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddLogMsg(arg1:string):Promise<void>;

export function GetCurrentVersion():Promise<string>;

export function HandleAction(arg1:string):Promise<void>;

export function LoadConfig():Promise<main.PokerDisplayConfig>;

export function SaveConfig(arg1:main.PokerDisplayConfig):Promise<void>;

export function ShowCommands():Promise<void>;

export function ShowWindow():Promise<void>;
